//! Sound: effects triggered by what the simulation reports, and music that
//! follows where you are (area themes, boss fights). The sounds themselves are
//! generated by `tools/gen_audio.py`.
//!
//! Nothing here feeds back into gameplay. With no audio device the game just
//! runs silently.

use std::collections::HashMap;

use bevy::audio::{AudioSink, AudioSinkPlayback, Volume};
use bevy::prelude::*;
use hk_sim::boss::{
    ArenaLock, Boss, BossAwoke, BossBrain, BossDefeated, BossPhaseChanged, BossState, Glyph,
};
use hk_sim::combat::{
    AttackDir, Blocked, CombatState, EnemyDied, Health, Hit, HitKind, PlayerDied, Team,
};
use hk_sim::components::{SimPos, Velocity};
use hk_sim::enemy::{Brain, EnemyState};
use hk_sim::player::{Motor, Player, PlayerState};
use hk_sim::world::progress::{AbilityGained, BenchRested};
use hk_sim::world::room::{CurrentRoom, RoomEntered, RoomLibrary, Theme};

use crate::interp::RenderPrepSet;
use crate::menu::Screen;
use crate::settings::Settings;

pub struct AudioPlugin;

impl Plugin for AudioPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<Sounds>()
            .init_resource::<Music>()
            .add_systems(PreStartup, load_sounds)
            .add_systems(
                Update,
                (
                    player_sounds,
                    combat_sounds,
                    enemy_sounds,
                    boss_sounds,
                    world_sounds,
                    music,
                )
                    .after(RenderPrepSet),
            );
    }
}

const SFX: &[&str] = &[
    "jump",
    "wall_jump",
    "land",
    "dash",
    "swing",
    "hit",
    "pogo",
    "hurt",
    "block",
    "enemy_die",
    "focus",
    "heal",
    "cast",
    "telegraph",
    "boss_toll",
    "boss_slam",
    "boss_roar",
    "boss_die",
    "bell_fall",
    "bell_hit",
    "bench",
    "pickup",
    "death",
    "ui_move",
    "ui_select",
    "door",
];

const TRACKS: &[&str] = &[
    "title",
    "ashen",
    "warrens",
    "cistern",
    "spire",
    "throne",
    "boss_matron",
    "boss_bellwarden",
];

#[derive(Resource, Default)]
pub struct Sounds {
    sfx: HashMap<&'static str, Handle<AudioSource>>,
    music: HashMap<&'static str, Handle<AudioSource>>,
}

fn load_sounds(mut sounds: ResMut<Sounds>, assets: Res<AssetServer>) {
    for n in SFX {
        sounds
            .sfx
            .insert(n, assets.load(format!("audio/sfx/{n}.wav")));
    }
    for n in TRACKS {
        sounds
            .music
            .insert(n, assets.load(format!("audio/music/{n}.wav")));
    }
}

/// Plays effect `name` once at `gain` (0..1), scaled by the volume settings.
pub fn play_sfx(
    commands: &mut Commands,
    sounds: &Sounds,
    settings: &Settings,
    name: &str,
    gain: f32,
) {
    let Some(h) = sounds.sfx.get(name) else {
        return;
    };
    let v = gain * settings.sfx * settings.master;
    if v <= 0.001 {
        return;
    }
    commands.spawn((
        AudioPlayer::new(h.clone()),
        PlaybackSettings::DESPAWN.with_volume(Volume::Linear(v)),
    ));
}

// ------------------------------------------------------------------ player --

#[derive(Default)]
struct PlayerMemory {
    grounded: bool,
    vy: f32,
    state: Option<PlayerState>,
    attacking: bool,
    wall_lock: u32,
    cast_lock: u32,
    hp: i32,
}

#[derive(Component)]
struct FocusLoop;

fn player_sounds(
    mut commands: Commands,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    mut mem: Local<PlayerMemory>,
    player: Query<(&Motor, &PlayerState, &Velocity, &CombatState, &Health), With<Player>>,
    focus: Query<Entity, With<FocusLoop>>,
) {
    let Ok((motor, state, vel, cs, hp)) = player.single() else {
        return;
    };
    // Jumping and landing.
    if mem.grounded && !motor.grounded && vel.y > 5.0 && motor.wall_lock == 0 {
        play_sfx(&mut commands, &sounds, &settings, "jump", 1.0);
    }
    if motor.wall_lock > 0 && mem.wall_lock == 0 {
        play_sfx(&mut commands, &sounds, &settings, "wall_jump", 1.0);
    }
    if !mem.grounded && motor.grounded && mem.vy < -7.0 {
        let g = (mem.vy.abs() / 20.0).clamp(0.35, 1.0);
        play_sfx(&mut commands, &sounds, &settings, "land", g);
    }
    // Dash, swing, cast.
    if *state == PlayerState::Dash && mem.state != Some(PlayerState::Dash) {
        play_sfx(&mut commands, &sounds, &settings, "dash", 1.0);
    }
    let attacking = cs.attack.is_some();
    if attacking && !mem.attacking {
        play_sfx(&mut commands, &sounds, &settings, "swing", 1.0);
    }
    if cs.cast_lock > 0 && mem.cast_lock == 0 {
        play_sfx(&mut commands, &sounds, &settings, "cast", 1.0);
    }
    // Healing: a shimmer while focusing, a chime when a mask comes back.
    if cs.focusing && focus.is_empty() {
        let v = 0.7 * settings.sfx * settings.master;
        commands.spawn((
            FocusLoop,
            AudioPlayer::new(sounds.sfx["focus"].clone()),
            PlaybackSettings::LOOP.with_volume(Volume::Linear(v)),
        ));
    }
    if !cs.focusing {
        for e in &focus {
            commands.entity(e).despawn();
        }
    }
    if hp.hp > mem.hp && mem.hp > 0 {
        play_sfx(&mut commands, &sounds, &settings, "heal", 1.0);
    }
    *mem = PlayerMemory {
        grounded: motor.grounded,
        vy: vel.y,
        state: Some(*state),
        attacking,
        wall_lock: motor.wall_lock,
        cast_lock: cs.cast_lock,
        hp: hp.hp,
    };
}

// ------------------------------------------------------------------ combat --

fn combat_sounds(
    mut commands: Commands,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    mut hits: MessageReader<Hit>,
    mut blocked: MessageReader<Blocked>,
    mut died: MessageReader<EnemyDied>,
    mut player_died: MessageReader<PlayerDied>,
) {
    for h in hits.read() {
        let name = match (h.victim_team, h.kind, h.attack_dir) {
            (Team::Player, _, _) => "hurt",
            (_, HitKind::Nail, AttackDir::Down) => "pogo",
            _ => "hit",
        };
        play_sfx(&mut commands, &sounds, &settings, name, 1.0);
    }
    for _ in blocked.read() {
        play_sfx(&mut commands, &sounds, &settings, "block", 1.0);
    }
    for _ in died.read() {
        play_sfx(&mut commands, &sounds, &settings, "enemy_die", 1.0);
    }
    for _ in player_died.read() {
        play_sfx(&mut commands, &sounds, &settings, "death", 1.0);
    }
}

/// An enemy starting its windup ticks, louder the closer it is.
fn enemy_sounds(
    mut commands: Commands,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    mut seen: Local<HashMap<Entity, EnemyState>>,
    player: Query<&SimPos, With<Player>>,
    enemies: Query<(Entity, &Brain, &SimPos)>,
) {
    let Ok(p) = player.single() else {
        return;
    };
    for (e, b, pos) in &enemies {
        if b.state == EnemyState::Windup && seen.get(&e) != Some(&EnemyState::Windup) {
            let d = (pos.0 - p.0).length();
            let g = (1.0 - d / 16.0).clamp(0.0, 1.0);
            if g > 0.05 {
                play_sfx(&mut commands, &sounds, &settings, "telegraph", g);
            }
        }
        seen.insert(e, b.state);
    }
    seen.retain(|e, _| enemies.contains(*e));
}

// -------------------------------------------------------------------- boss --

#[derive(Default)]
struct BossMemory {
    state: Option<BossState>,
    grounded: bool,
    hit_wall: bool,
    glyphs: usize,
}

fn boss_sounds(
    mut commands: Commands,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    mut mem: Local<BossMemory>,
    mut awoke: MessageReader<BossAwoke>,
    mut phase: MessageReader<BossPhaseChanged>,
    mut beaten: MessageReader<BossDefeated>,
    bosses: Query<&BossBrain, With<Boss>>,
    glyphs: Query<&Glyph>,
) {
    for _ in awoke.read() {
        play_sfx(&mut commands, &sounds, &settings, "boss_roar", 1.0);
    }
    for _ in phase.read() {
        play_sfx(&mut commands, &sounds, &settings, "boss_roar", 1.0);
    }
    for _ in beaten.read() {
        play_sfx(&mut commands, &sounds, &settings, "boss_die", 1.0);
    }
    if let Some(b) = bosses.iter().next() {
        if mem.state != Some(b.state) && b.state == BossState::Telegraph {
            play_sfx(&mut commands, &sounds, &settings, "boss_toll", 0.9);
        }
        if b.state == BossState::Active && b.was_grounded && !mem.grounded {
            play_sfx(&mut commands, &sounds, &settings, "boss_slam", 1.0);
        }
        if b.hit_wall && !mem.hit_wall {
            play_sfx(&mut commands, &sounds, &settings, "boss_slam", 1.0);
        }
        *mem = BossMemory {
            state: Some(b.state),
            grounded: b.was_grounded,
            hit_wall: b.hit_wall,
            glyphs: glyphs.iter().count(),
        };
        return;
    }
    // A glyph vanishing means a bell was let go.
    let now = glyphs.iter().count();
    if now < mem.glyphs {
        play_sfx(&mut commands, &sounds, &settings, "bell_fall", 0.8);
    }
    mem.glyphs = now;
}

// ------------------------------------------------------------------- world --

fn world_sounds(
    mut commands: Commands,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    mut rested: MessageReader<BenchRested>,
    mut gained: MessageReader<AbilityGained>,
    mut entered: MessageReader<RoomEntered>,
    current: Res<CurrentRoom>,
    mut last_room: Local<String>,
) {
    for _ in rested.read() {
        play_sfx(&mut commands, &sounds, &settings, "bench", 1.0);
    }
    for _ in gained.read() {
        play_sfx(&mut commands, &sounds, &settings, "pickup", 1.0);
    }
    if entered.read().count() > 0 {
        if *last_room != current.id && !last_room.is_empty() {
            play_sfx(&mut commands, &sounds, &settings, "door", 1.0);
        }
        *last_room = current.id.clone();
    }
}

// ------------------------------------------------------------------- music --

#[derive(Resource, Default)]
struct Music {
    /// The track that should be playing now, and the entity playing it.
    current: Option<(&'static str, Entity)>,
    /// Tracks fading out: (entity, volume).
    fading: Vec<(Entity, f32)>,
    /// 0..1 fade-in of the current track.
    fade_in: f32,
}

#[derive(Component)]
struct MusicTrack;

const TRACK_GAIN: f32 = 0.9;
const FADE_SECS: f32 = 1.2;

fn theme_track(t: Theme) -> &'static str {
    match t {
        Theme::Sandbox | Theme::Ashen => "ashen",
        Theme::Warrens => "warrens",
        Theme::Cistern => "cistern",
        Theme::Spire => "spire",
        Theme::Throne => "throne",
    }
}

fn wanted_track(
    screen: &Screen,
    lock: &ArenaLock,
    bosses: &Query<&Boss>,
    library: &RoomLibrary,
    current: &CurrentRoom,
) -> Option<&'static str> {
    if matches!(screen, Screen::Title) {
        return Some("title");
    }
    if lock.0 {
        if let Some(b) = bosses.iter().next() {
            return Some(if b.id == "matron" {
                "boss_matron"
            } else {
                "boss_bellwarden"
            });
        }
    }
    library.get(&current.id).map(|d| theme_track(d.theme))
}

#[allow(clippy::too_many_arguments)]
fn music(
    mut commands: Commands,
    time: Res<Time<Real>>,
    sounds: Res<Sounds>,
    settings: Res<Settings>,
    screen: Res<Screen>,
    lock: Res<ArenaLock>,
    library: Res<RoomLibrary>,
    current: Res<CurrentRoom>,
    bosses: Query<&Boss>,
    mut state: ResMut<Music>,
    mut sinks: Query<&mut AudioSink, With<MusicTrack>>,
) {
    let dt = time.delta_secs();
    let want = wanted_track(&screen, &lock, &bosses, &library, &current);
    let playing = state.current.map(|(n, _)| n);
    if want != playing {
        // Fade the old track out, start the new one silent.
        if let Some((_, e)) = state.current.take() {
            let v = sinks
                .get(e)
                .map(|s| s.volume().to_linear())
                .unwrap_or_default();
            state.fading.push((e, v));
        }
        if let Some(n) = want {
            if let Some(h) = sounds.music.get(n) {
                let e = commands
                    .spawn((
                        MusicTrack,
                        AudioPlayer::new(h.clone()),
                        PlaybackSettings::LOOP.with_volume(Volume::Linear(0.0)),
                    ))
                    .id();
                state.current = Some((n, e));
                state.fade_in = 0.0;
            }
        }
    }
    let target = TRACK_GAIN * settings.music * settings.master;
    state.fade_in = (state.fade_in + dt / FADE_SECS).min(1.0);
    if let Some((_, e)) = state.current {
        if let Ok(mut sink) = sinks.get_mut(e) {
            // Quieter in menus, so the options sliders are audible.
            let duck = if matches!(*screen, Screen::Playing) {
                1.0
            } else {
                0.6
            };
            sink.set_volume(Volume::Linear(target * state.fade_in * duck));
        }
    }
    let step = dt / FADE_SECS;
    let mut still = Vec::new();
    for (e, v) in std::mem::take(&mut state.fading) {
        let v = v - step * target.max(0.05);
        if v <= 0.0 {
            commands.entity(e).despawn();
        } else {
            if let Ok(mut sink) = sinks.get_mut(e) {
                sink.set_volume(Volume::Linear(v));
            }
            still.push((e, v));
        }
    }
    state.fading = still;
}
