#!/usr/bin/env python3
"""Room builder: authors the world as code and writes assets/rooms/*.room.ron.

The RON files are what the game reads; this script is just a convenient way to
author them (rects and platforms instead of hand-typed ASCII). Run it from the
repo root:

    python3 tools/build_rooms.py            # write every room
    python3 tools/build_rooms.py --show B1  # print one room's map

Then check the result with `cargo run --release -p hk_tools --bin lint_rooms`.

Coordinates: x to the right, y UP, in tiles; (0, 0) is the bottom-left corner.
`top` arguments are the y of a surface (where feet stand), so a platform with
top=5 is one you stand on at y = 5.

Room shell: solid outer walls, a floor `floor` tiles thick (its top is y=floor)
and a one-tile ceiling. Doorways are cut into the shell with door_*/hatch_*.
"""

import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "assets", "rooms")

DOOR_H = 4  # doorways are this many tiles tall


class Room:
    def __init__(self, rid, name, theme, w, h, floor=2):
        self.id, self.name, self.theme = rid, name, theme
        self.w, self.h, self.floor = w, h, floor
        self.cells = [["." for _ in range(w)] for _ in range(h)]
        self.spawns, self.entries, self.exits = [], [], []
        self.benches, self.pickups = [], []
        self.fill(0, 0, w, floor, "#")
        self.fill(0, 0, 1, h, "#")
        self.fill(w - 1, 0, 1, h, "#")
        self.fill(0, h - 1, w, 1, "#")

    # ---- geometry ----
    def fill(self, x, y, w, h, c):
        for j in range(y, min(y + h, self.h)):
            for i in range(x, min(x + w, self.w)):
                if 0 <= i and 0 <= j:
                    self.cells[j][i] = c
        return self

    def air(self, x, y, w, h):
        return self.fill(x, y, w, h, ".")

    def block(self, x, w, top, y0=None):
        """Solid from y0 (default: the floor) up to `top`."""
        y0 = self.floor if y0 is None else y0
        return self.fill(x, y0, w, top - y0, "#")

    def slab(self, x, w, top, thick=1):
        """A solid platform, `thick` tiles thick, standing surface at `top`."""
        return self.fill(x, top - thick, w, thick, "#")

    def plat(self, x, w, top):
        """A one-way (jump-through) platform, surface at `top`."""
        return self.fill(x, top - 1, w, 1, "=")

    def spikes(self, x, w, y=None):
        y = self.floor if y is None else y
        return self.fill(x, y, w, 1, "^")

    # ---- doorways ----
    def door_left(self, y, to, entry):
        self.air(0, y, 1, DOOR_H)
        self.exits.append(((0.0, float(y), 1.5, float(DOOR_H)), to, entry))

    def door_right(self, y, to, entry):
        self.air(self.w - 1, y, 1, DOOR_H)
        self.exits.append(((self.w - 1.5, float(y), 1.5, float(DOOR_H)), to, entry))

    def hatch_floor(self, x, w, to, entry):
        """A hole in the floor; falling in leaves the room."""
        self.air(x, 0, w, self.floor)
        self.exits.append(((float(x), float(self.floor - 1), float(w), 1.0), to, entry))

    def hatch_ceiling(self, x, w, to, entry):
        """An opening in the ceiling; jumping into it leaves the room."""
        self.air(x, self.h - 1, w, 1)
        self.exits.append(((float(x), self.h - 2.5, float(w), 3.5), to, entry))

    # ---- things ----
    def entry(self, name, x, y, facing=1):
        self.entries.append((name, float(x), float(y), facing))

    def spawn(self, kind, x, y, persistent=False):
        self.spawns.append((kind, float(x), float(y), persistent))

    def bench(self, x, y):
        self.benches.append((float(x), float(y)))

    def pickup(self, ability, x, y):
        self.pickups.append((ability, float(x), float(y)))

    # ---- output ----
    def rows(self):
        return ["".join(r) for r in reversed(self.cells)]

    def ron(self):
        f = lambda v: f"{v:.1f}"
        o = [f'// {self.name} ({self.id}). Generated by tools/build_rooms.py; edit that, not this.']
        o.append("(")
        o.append(f'    id: "{self.id}",')
        o.append(f'    name: "{self.name}",')
        o.append(f"    theme: {self.theme},")
        o.append("    tiles: [")
        for r in self.rows():
            o.append(f'        "{r}",')
        o.append("    ],")
        o.append("    spawns: [")
        for kind, x, y, pers in self.spawns:
            extra = ", persistent: true" if pers else ""
            o.append(f"        (kind: {kind}, at: ({f(x)}, {f(y)}){extra}),")
        o.append("    ],")
        o.append("    entries: [")
        for name, x, y, facing in self.entries:
            o.append(f'        (name: "{name}", at: ({f(x)}, {f(y)}), facing: {facing}),')
        o.append("    ],")
        o.append("    exits: [")
        for (x, y, w, h), to, entry in self.exits:
            o.append(f'        (rect: ({f(x)}, {f(y)}, {f(w)}, {f(h)}), to: "{to}", entry: "{entry}"),')
        o.append("    ],")
        o.append("    benches: [")
        for x, y in self.benches:
            o.append(f"        (at: ({f(x)}, {f(y)})),")
        o.append("    ],")
        o.append("    pickups: [")
        for ab, x, y in self.pickups:
            o.append(f"        (ability: {ab}, at: ({f(x)}, {f(y)})),")
        o.append("    ],")
        o.append(")")
        return "\n".join(o) + "\n"


rooms = []


def new(*a, **k):
    r = Room(*a, **k)
    rooms.append(r)
    return r


# =========================================================== A: Ashen Descent ==
# The tutorial. Nothing here needs an ability. It is mostly FIGHTING: a training
# dummy and the first Husk in the very first room, then platforms you can
# simply walk and hop down, a bench, and only small spike hazards.


def build_A1():
    r = new("A1", "The Landing", "Ashen", 44, 16)
    r.entry("start", 4, 2, 1)
    r.entry("hatch", 36, 2, -1)
    r.spawn("Dummy", 7, 2)  # three tiles from the start: learn to strike
    r.spawn("Husk", 20, 2)  # the first fight, ~10 seconds in
    r.block(28, 2, 3)  # a little jump practice, after the fight
    r.block(31, 3, 4)
    r.hatch_floor(40, 3, "A2", "top")


def build_A2():
    r = new("A2", "Broken Ledges", "Ashen", 56, 20)
    r.entry("top", 4, 13, 1)
    r.entry("east", 52, 2, -1)
    r.block(1, 9, 13)  # the arrival ledge (solid to the floor)
    # Wide platforms, one-tile gaps, three-tile drops: walk off and land.
    r.plat(10, 6, 10)
    r.plat(17, 7, 7)
    r.plat(25, 6, 4)
    r.spikes(33, 3)  # one small patch to hop over
    r.spawn("Dummy", 34.5, 4)  # an optional pogo target above it
    r.spawn("Husk", 20, 7)  # on the middle platform
    r.spawn("Husk", 40, 2)
    r.bench(47, 2)  # the first bench, before the door
    r.hatch_ceiling(3, 4, "A1", "hatch")
    r.door_right(2, "A3", "west")


def build_A3():
    r = new("A3", "First Husk", "Ashen", 48, 14)
    r.entry("west", 4, 2, 1)
    r.entry("east", 44, 2, -1)
    r.block(11, 2, 3)
    r.block(20, 5, 4)
    r.spawn("Husk", 17, 2)
    r.spawn("Wisp", 26, 6)  # a flier: the first thing that is not on the ground
    r.spawn("Husk", 31, 2)
    r.bench(41, 2)
    r.door_left(2, "A2", "east")
    r.door_right(2, "A4", "west")


def build_A4():
    r = new("A4", "The Spike Pit", "Ashen", 56, 18)
    r.entry("west", 4, 2, 1)
    r.entry("east", 52, 2, -1)
    r.spikes(23, 8)  # one pit, crossed by a stepping platform (or by pogo)
    r.plat(25, 4, 5)
    r.spawn("Wisp", 26, 9)  # hovers over the pit: fight it, or pogo it across
    r.spawn("Husk", 40, 2)
    r.spawn("Wisp", 34, 10)
    r.door_left(2, "A3", "east")
    r.door_right(2, "B1", "west")


# ============================================================ B: Gutterglow ==
# The hub, a nest, a shaft, and the Matron who guards the Dash.


def build_B1():
    r = new("B1", "Gutterglow Hub", "Warrens", 64, 28)
    r.entry("west", 4, 2, 1)
    r.entry("east", 60, 2, -1)
    r.entry("hatch", 47, 2, 1)  # climbing back up from the Cistern
    r.entry("north", 60, 20, -1)  # back from the Spire
    r.entry("chute", 34, 25, 1)  # dropping in from the Spire's shortcut
    r.bench(30, 2)
    # A staircase of thin platforms up to the high ledge.
    for i, x in enumerate([13, 21, 29, 37, 45]):
        r.plat(x, 5, 5 + 3 * i)
    r.slab(54, 9, 20, 2)  # the high ledge
    r.spawn("Husk", 18, 2)
    r.spawn("Wisp", 36, 17)
    r.hatch_floor(51, 4, "C1", "top")
    r.door_left(2, "A4", "east")
    r.door_right(2, "B2", "west")
    r.door_right(20, "D1", "bottom")


def build_B2():
    r = new("B2", "Husk Nest", "Warrens", 60, 16)
    r.entry("west", 4, 2, 1)
    r.entry("east", 56, 2, -1)
    r.block(14, 6, 4)
    r.block(30, 6, 5)
    r.plat(20, 8, 8)
    r.plat(38, 8, 8)
    for x in (24, 41):
        r.spawn("Husk", x, 2)
    r.spawn("Husk", 16, 4)  # on top of the first block
    r.spawn("Husk", 33, 5)  # on top of the taller block
    r.spawn("Wisp", 32, 10)
    r.door_left(2, "B1", "east")
    r.door_right(2, "B3", "west")


def build_B3():
    r = new("B3", "Wisp Shaft", "Warrens", 30, 48)
    r.entry("west", 4, 2, 1)
    r.entry("top", 24, 41, -1)
    # Alternate sides, three tiles higher each time.
    top = 5
    left = True
    while top <= 41:
        if left:
            r.plat(2, 9, top)
        else:
            r.plat(16, 11, top)
        left = not left
        top += 3
    r.slab(17, 12, 41, 2)  # the summit
    r.air(1, 41, 16, 1)
    r.bench(22, 41)
    for x, y in [(14, 14), (20, 26), (10, 34)]:
        r.spawn("Wisp", x, y)
    r.door_left(2, "B2", "east")
    r.door_right(41, "B4", "west")


def build_B4():
    r = new("B4", "Matron's Den", "Warrens", 44, 14, floor=1)
    r.entry("west", 4, 1, 1)
    r.spawn("Matron", 34, 1, persistent=True)
    r.door_left(1, "B3", "top")


# ============================================================== C: Cistern ==
# Needs Dash. Ends at the shrine that teaches Wall Grip.


def build_C1():
    r = new("C1", "Flooded Walk", "Cistern", 64, 18)
    r.entry("top", 5, 13, 1)
    r.entry("east", 60, 2, -1)
    r.block(1, 11, 13)  # arrival block, solid to the floor
    # Stairs of thin platforms down to the floor (and back up again).
    r.plat(14, 4, 10)
    r.plat(19, 4, 7)
    r.plat(24, 3, 4)
    r.spikes(33, 6)  # six tiles of spikes: only a dash crosses
    r.spawn("Husk", 42, 2)
    r.spawn("Husk", 45, 2)
    r.spawn("Spitter", 46, 2)
    r.hatch_ceiling(3, 4, "B1", "hatch")
    r.door_right(2, "C2", "west")


def build_C2():
    r = new("C2", "Shield Gallery", "Cistern", 68, 16)
    r.entry("west", 4, 2, 1)
    r.entry("east", 64, 2, -1)
    r.bench(7, 2)
    for x in (16, 28, 40, 52):
        r.block(x, 2, 5)
    for x in (13, 37):
        r.plat(x, 14, 9)
    r.spawn("Shieldbearer", 21, 2)
    r.spawn("Shieldbearer", 34, 2)
    r.spawn("Shieldbearer", 48, 2)
    r.spawn("Spitter", 19, 9)
    r.spawn("Spitter", 44, 9)
    r.door_left(2, "C1", "east")
    r.door_right(2, "C3", "west")


def build_C3():
    r = new("C3", "Bell Shaft", "Cistern", 36, 54)
    r.entry("west", 4, 2, 1)
    r.entry("top", 30, 46, -1)
    r.spikes(9, 26)  # the rest of the shaft floor is spikes
    # Eight tiles from the floor's edge to the first platform: dash.
    r.plat(17, 9, 4)
    top = 7
    left = True
    while top <= 46:
        if left:
            r.plat(3, 9, top)
        else:
            r.plat(17, 9, top)
        left = not left
        top += 3
    r.slab(26, 9, 46, 2)  # the summit
    r.bench(30, 46)
    for x, y in [(14, 16), (24, 30), (10, 38)]:
        r.spawn("Wisp", x, y)
    r.spawn("Spitter", 22, 40)
    r.door_left(2, "C2", "east")
    r.door_right(46, "C4", "top")


def build_C4():
    r = new("C4", "Grip Shrine", "Cistern", 40, 30)
    r.entry("top", 4, 22, 1)
    r.block(1, 8, 22)  # the arrival block (top y = 22): its face is the wall to climb
    r.pickup("WallGrip", 34, 2)
    r.spawn("Husk", 20, 2)
    r.spawn("Husk", 28, 2)
    r.door_left(22, "C3", "top")


# ============================================================ D: Lantern Spire ==
# Needs Wall Grip. Ends with the Bellwarden.


def build_D1():
    r = new("D1", "The Ascent", "Spire", 24, 64)
    r.entry("bottom", 12, 2, 1)
    r.entry("top", 20, 58, -1)
    # A six-wide shaft between two thick walls.
    r.fill(1, 2, 8, 58, "#")
    r.fill(15, 2, 8, 58, "#")
    # An antechamber at the bottom, with the door back to the hub.
    r.air(1, 2, 8, 4)
    r.door_left(2, "B1", "north")
    # Alcoves cut into the walls where you can catch your breath (and fight).
    r.air(15, 22, 6, 4)
    r.air(3, 40, 6, 4)
    r.spawn("Husk", 17, 22)
    r.spawn("Shieldbearer", 5, 40)
    r.spawn("Wisp", 12, 30)
    r.spawn("Wisp", 12, 50)
    # The way out: a corridor to the right at the top.
    r.air(15, 58, 8, 4)
    r.door_right(58, "D2", "west")


def build_D2():
    r = new("D2", "Bell-Keeper's Rest", "Spire", 40, 16)
    r.entry("west", 4, 2, 1)
    r.entry("east", 36, 2, -1)
    r.bench(20, 2)
    r.hatch_floor(28, 4, "B1", "chute")
    r.door_left(2, "D1", "top")
    r.door_right(2, "D3", "west")


def build_D3():
    r = new("D3", "The Gauntlet", "Spire", 84, 22)
    r.entry("west", 4, 2, 1)
    r.entry("east", 80, 2, -1)
    # 1: husks and thin platforms
    r.plat(10, 5, 6)
    r.spawn("Husk", 17, 2)
    r.spawn("Husk", 22, 2)
    # 2: a dash over spikes
    r.spikes(27, 6)
    r.spawn("Wisp", 30, 9)
    # 3: a wall to climb
    r.block(46, 6, 10)
    r.spawn("Husk", 42, 2)
    # 4: shields and spit
    r.plat(56, 12, 7)
    r.spawn("Shieldbearer", 58, 2)
    r.spawn("Shieldbearer", 66, 2)
    r.spawn("Spitter", 62, 7)
    # 5: a bench before the throne
    r.bench(76, 2)
    r.door_left(2, "D2", "east")
    r.door_right(2, "D4", "west")


def build_D4():
    r = new("D4", "The Hollow Throne", "Throne", 44, 14, floor=1)
    r.entry("west", 4, 1, 1)
    r.spawn("Bellwarden", 34, 1, persistent=True)
    r.door_left(1, "D3", "east")


for fn in [
    build_A1, build_A2, build_A3, build_A4,
    build_B1, build_B2, build_B3, build_B4,
    build_C1, build_C2, build_C3, build_C4,
    build_D1, build_D2, build_D3, build_D4,
]:
    fn()


def main():
    args = sys.argv[1:]
    if args[:1] == ["--show"]:
        for r in rooms:
            if r.id == args[1]:
                print(f"{r.id} {r.name}  {r.w}x{r.h}")
                for j, row in enumerate(r.rows()):
                    print(f"{r.h - 1 - j:3d} {row}")
                return
        sys.exit(f"no room {args[1]}")
    os.makedirs(OUT, exist_ok=True)
    for r in rooms:
        path = os.path.join(OUT, f"{r.id}.room.ron")
        with open(path, "w") as fh:
            fh.write(r.ron())
    print(f"wrote {len(rooms)} rooms to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
